apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- hpa.yaml

labels:
- pairs:
    app: admin-ui
    component: frontend
    part-of: bbapp

images:
- name: admin-ui-image
  newName: asia-south1-docker.pkg.dev/bb-app-461714/bbapp-images/admin-ui
  newTag: placeholder
