apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-ui-config
data:
  # Override development-specific values
  ENVIRONMENT: "dev"
  NEXT_PUBLIC_APP_URL: "https://dev-admin.bbcloud.app"
  NEXT_PUBLIC_API_BASE_URL: "http://api.bbapp-dev.svc.cluster.local:8080"
  
